PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE village (id int, name varchar(20));
CREATE TABLE blog ( id int ,content varchar(255));
CREATE TABLE blogs ( id int ,content varchar(255));
INSERT INTO "blogs" VALUES(1,'sdlfksdlfk');
INSERT INTO "blogs" VALUES(1,'sdlfksdlfk');
INSERT INTO "blogs" VALUES(1,'sdlfksdlfk');
INSERT INTO "blogs" VALUES(1,'sdlfksdlfk');
INSERT INTO "blogs" VALUES(1,'sdlfksdlfk');
INSERT INTO "blogs" VALUES(1,'sdlfksdlfk');
CREATE TABLE proverbs ( id integer PRIMARY KEY AUTOINCREMENT,
content varchar(255),
author varchar(255),
create_dt varchar(255)
);
INSERT INTO "proverbs" VALUES(23,'백년을 살 것처럼 일하고 내일 죽을 것처럼 기도하라','프랭클린)',NULL);
INSERT INTO "proverbs" VALUES(24,'부유함이 문명을 낳지는 못하나','문명은 부유함을 낳는다',NULL);
INSERT INTO "proverbs" VALUES(25,'가난한 사람은 덕행으로','부자는 선행으로 이름을 떨쳐야 한다',NULL);
INSERT INTO "proverbs" VALUES(26,'시종일관하는 자는 운명을 믿고','변덕 부리는 자는 요행을 믿는다',NULL);
INSERT INTO "proverbs" VALUES(27,'인간의 진정한 재산은 그가 이 세상에서 행하는 선행인 것이다','마호메트)',NULL);
INSERT INTO "proverbs" VALUES(28,'자신이 현명하다고 생각하고 있는 인간은 정녕 구제할 수 없는 바보이다','볼테르)',NULL);
INSERT INTO "proverbs" VALUES(29,'얻기 어려운 것은 시기(時期)요','놓치기 쉬운 것은 기회이다',NULL);
INSERT INTO "proverbs" VALUES(30,'누구나 오래 살기를 바란다. 그러나 누구를 막론하고 나이는 먹기 싫어한다','스위프트)',NULL);
INSERT INTO "proverbs" VALUES(31,'술은 인격을 비춰주는 거울이다','아르케시우스)',NULL);
INSERT INTO "proverbs" VALUES(32,'충실한 삶의 깊이를 아는 자는 아름다운 죽음의 가치를 안다','테오도르)',NULL);
INSERT INTO "proverbs" VALUES(33,'가장 훌륭한 기술','가장 배우기 어려운 기술은 세상을 살아가는 기술이다',NULL);
INSERT INTO "proverbs" VALUES(34,'여가를 활용하지 못하는 사람은 항상 여가 시간이 없다','서양 격언)',NULL);
INSERT INTO "proverbs" VALUES(35,'가장 최상의 길은 없다. 많은 사람이 가고 있다면 그 길이 최상이다','루신)',NULL);
INSERT INTO "proverbs" VALUES(36,'죽음을 두려워하는 나머지 삶을 시작조차 못하는 사람이 많다','벤다이크)',NULL);
INSERT INTO "proverbs" VALUES(37,'신념은 연애와 같은 것이어서 강요할 수 없는 것이다','쇼펜하우어)',NULL);
INSERT INTO "proverbs" VALUES(38,'속이는 말로 재물을 모으는 것은 죽음을 구하는 것이다','성경 잠언)',NULL);
INSERT INTO "proverbs" VALUES(39,'말이 입힌 상처는 칼이 입힌 상처보다 깁다','모르코 속담)',NULL);
INSERT INTO "proverbs" VALUES(40,'이해가 부족한 사람이 오해가 많은 사람보다 낫다','아나톨 프랑스)',NULL);
INSERT INTO "proverbs" VALUES(41,'한 시대의 철학은 다음 시대에서는 평범한 상식에 불과하다','헨리 W. 비치)',NULL);
INSERT INTO "proverbs" VALUES(42,'결함이 나의 출발의 바탕이고 무능이 나의 근원이다','발레리)',NULL);
INSERT INTO "proverbs" VALUES(43,'현실에 대한 눈은 감을수 있어도 기억에 대한 눈은 감을 수 없다','스타니스러우 J. 룩)',NULL);
INSERT INTO "proverbs" VALUES(44,'생각이 깊지 못한 사람은 항상 입을 놀린다','호머)',NULL);
INSERT INTO "proverbs" VALUES(45,'부지런한 바보만큼 이웃을 괴롭히는 자는 없다','H. 가이야)',NULL);
INSERT INTO "proverbs" VALUES(46,'무지함을 두려워 말라. 거짓 지식을 두려워하라','파스칼)',NULL);
INSERT INTO "proverbs" VALUES(47,'자신의 행동이 빗나간 사람일수록 맨 먼저 남을 모략한다','몰리에르)',NULL);
INSERT INTO "proverbs" VALUES(48,'인간이란 생각하는 것이 적으면 적을수록 많이 지껄여댄다','몽테스키외)',NULL);
INSERT INTO "proverbs" VALUES(49,'남은 많이 용서하되 자신은 결코 용서하지 말라','푸블릴리우스 시루스)',NULL);
INSERT INTO "proverbs" VALUES(50,'사람은 자기 일보다 남의 일을 더 잘알고 더 잘 판단한다','테렌티우스)',NULL);
INSERT INTO "proverbs" VALUES(51,'눔을 감아라. 그럼 너는 너 자신을 볼 수 있으리라','버틀러)',NULL);
INSERT INTO "proverbs" VALUES(52,'군자는 의리에 밝고','소인은 이익에 밝다',NULL);
INSERT INTO "proverbs" VALUES(53,'눈물을 흘리면서 빵을 먹어보지 못한 사람은 인생의 참맛을 알 수 없다','괴테)',NULL);
INSERT INTO "proverbs" VALUES(54,'굳은 결심은 가장 유용한 지식이다','나폴레옹)',NULL);
INSERT INTO "proverbs" VALUES(55,'선을 행하는 데는 나중이라는 말이 필요없다','괴테)',NULL);
INSERT INTO "proverbs" VALUES(56,'학문의 최대의 적은 자기 마음속에 있는 유혹이다','처칠)',NULL);
INSERT INTO "proverbs" VALUES(57,'기대하지 않는 자는 실망하지도 않을 것이다','울거터)',NULL);
INSERT INTO "proverbs" VALUES(58,'좋은 밤을 찾다가 좋은 낮을 잃어버리는 사람들이 많다','네델란드 격언)',NULL);
INSERT INTO "proverbs" VALUES(59,'악은 쾌락 속에서도 고통을 주지만 덕은 고통속에서도 위안을 준다','콜튼)',NULL);
INSERT INTO "proverbs" VALUES(60,'환락은 망상 위에 세울 수 있으나','행복은 진리 위에만 세워진다',NULL);
INSERT INTO "proverbs" VALUES(61,'어느날 갑자기 착한 사람이 되거나 악인이 되는 사람은 없다','시드니)',NULL);
INSERT INTO "proverbs" VALUES(62,'많은 벗을 가진 사람은 한 사람의 진실한 벗을 가질 수 없다','아리스토텔레스)',NULL);
INSERT INTO "proverbs" VALUES(63,'지성인은 자기의 마음으로 자기 자신을 망보는 사람이다','까뮈)',NULL);
INSERT INTO "proverbs" VALUES(64,'어떠한 충고일지라도 길게 말하지 말라','호라티우스)',NULL);
INSERT INTO "proverbs" VALUES(65,'남자는 마음으로 늙고 여자는 얼굴로 늙는다','서양속담)',NULL);
INSERT INTO "proverbs" VALUES(66,'친구를 얻는 유일한 방법은 스스로 완전한 친구가 되는 것이다','에머슨)',NULL);
INSERT INTO "proverbs" VALUES(67,'지식과 목재는 세파에 시달리지 아니하면 많이 애용될 수가 없다','올리버 웬델 홈즈)',NULL);
INSERT INTO "proverbs" VALUES(68,'거룩하고 즐겁고 활기차게 살아라. 믿음과 열심에는 피곤과 짜증이 없다','어네스트 홈즈)',NULL);
INSERT INTO "proverbs" VALUES(69,'아무리 화려한 궁전이라도 초라한 내 집만한 곳은 없다','페인)',NULL);
INSERT INTO "proverbs" VALUES(70,'하나의 모범은 천 마디의 논쟁보다 더 가치 있는 것이다','토마스 카알라일)',NULL);
INSERT INTO "proverbs" VALUES(71,'당신은 의지의 주인이 되라. 그리고 당신은 양심의 노예가 되라','유태 속담)',NULL);
INSERT INTO "proverbs" VALUES(72,'작은 도끼라도 찍고 찍으면 큰 참나무는 넘어진다','세익스피어)',NULL);
INSERT INTO "proverbs" VALUES(73,'행동을 초래시키지 않는 생각','그것은 생각이 아니라 공상이다',NULL);
INSERT INTO "proverbs" VALUES(74,'민주주의의 모든 질병은 더 많은 민주주의에 의해서 치료될 수 있다','알프레드 스미스)',NULL);
INSERT INTO "proverbs" VALUES(75,'용기가 없는 사람에게는 어떤 좋은 것도 생기지 않는다','마르쿠스 아우렐리우스)',NULL);
INSERT INTO "proverbs" VALUES(76,'오직 바보나 죽은 자만이 절대로 자기의 의견을 변화시키지 않는다','제임스 럿셀 로우웰)',NULL);
INSERT INTO "proverbs" VALUES(77,'큰 시련은 큰 의무를 완수하게 만드는 것이다','톰슨)',NULL);
INSERT INTO "proverbs" VALUES(78,'배운 사람은 항상 자기 속에 재산이 있다','필래드라스)',NULL);
INSERT INTO "proverbs" VALUES(79,'적당주의자가 되지 말라. 그것은 세상에서 가장 위험한 것이다','휴그 왈폴)',NULL);
INSERT INTO "proverbs" VALUES(80,'자연은 하나님의 작품이요. 예술은 사람의 작품이다','롱펠로우)',NULL);
INSERT INTO "proverbs" VALUES(81,'편견이란 실효성이 없는 의견이다','암브로스 빌)',NULL);
INSERT INTO "proverbs" VALUES(82,'선한 사람이 되라. 그러면 세상은 선한 세상이 될 것이다','힌두교 속담)',NULL);
INSERT INTO "proverbs" VALUES(83,'인류를 위해 사는 것은 자기의 이름을 위해 사는 것보다 훌륭한 것이다','바첼 린드세이)',NULL);
INSERT INTO "proverbs" VALUES(84,'작지만 청결한 것은 큰 것이요. 크지만 불결한 것은 작은 것이다','바이)',NULL);
INSERT INTO "proverbs" VALUES(85,'기쁨을 주는 사람만이 더 많은 기쁨을 즐길 수 있다','알렉산더 듀마)',NULL);
INSERT INTO "proverbs" VALUES(86,'너 자신을 다스려라. 그러면 당신은 세계를 다스릴 것이다','중국 속담)',NULL);
INSERT INTO "proverbs" VALUES(87,'작은 구멍 하나가 큰 배를 침몰시키는 것이다','에프라임 도마라츠키)',NULL);
INSERT INTO "proverbs" VALUES(88,'성실하지 못한 사람은 위대한 것들을 생산할 수가 없다','제임스 럿셀 로우웰)',NULL);
INSERT INTO "proverbs" VALUES(89,'목표를 보는 자는 장애물을 겁내지 않는다','한나 모어)',NULL);
INSERT INTO "proverbs" VALUES(90,'산을 옮기는 사람은 작은 돌맹이부터 옮긴다','중국 속담)',NULL);
INSERT INTO "proverbs" VALUES(91,'세상이 당신에게 준 것보다 더 많이 세상에게 주라','헨리 포드)',NULL);
INSERT INTO "proverbs" VALUES(92,'험담은 세 사람을 죽인다. 말하는 자','험담의 대상자',NULL);
INSERT INTO "proverbs" VALUES(93,'핑계를 잘 대는 사람은 거의 좋은 일을 하나도 해내지 못한다','벤자민 프랭클린)',NULL);
INSERT INTO "proverbs" VALUES(94,'겸손이 없다면 당신은 인생의 가장 기본적인 교훈도 배울 수가 없다','존 톰슨)',NULL);
INSERT INTO "proverbs" VALUES(95,'작은 성공을 만족스럽게 생각하는 사람은 큰 성공을 얻지 못한다','제세 메서 게만)',NULL);
INSERT INTO "proverbs" VALUES(96,'나는 내 운명의 주인이요. 나는 내 마음의 선장이다','윌리암 어네스트 헨리)',NULL);
INSERT INTO "proverbs" VALUES(97,'존재하는 것을 변화시키는 것은 성숙하게 만드는 것이다','헨리 버그슨)',NULL);
INSERT INTO "proverbs" VALUES(98,'인격은 당신의 아이들에게 남겨줄 수 있는 최대의 유산이다','아놀드 그라소우)',NULL);
INSERT INTO "proverbs" VALUES(99,'과도한 재산을 소유하게 되었을 때보다 더 시련을 당하게 되는 적은 없다','레우 왈레이스)',NULL);
INSERT INTO "proverbs" VALUES(100,'행동가처럼 생각하라. 그리고 생각하는 사람처럼 행동하라','헨리 버그슨)',NULL);
INSERT INTO "proverbs" VALUES(101,'소유물의 부족은 개선할 수 있으나 영혼의 가난은 해결하기 쉬운 것이 아니다','몽테뉴)',NULL);
INSERT INTO "proverbs" VALUES(102,'당신의 인생은 당신이 하루종일 무슨 생각을 하는지에 달려있다','에머슨)',NULL);
INSERT INTO "proverbs" VALUES(103,'하나님 앞에서는 울어라. 그러나 사람들 앞에서는 웃어하','유태 속담)',NULL);
INSERT INTO "proverbs" VALUES(104,'인내하라.경험하라.조심하라. 그리고 희망을 가져라','조셉 에디슨)',NULL);
INSERT INTO "proverbs" VALUES(105,'위대한 사람은 절대로 기회가 부족하다고 불평하지 않는다','에머슨)',NULL);
INSERT INTO "proverbs" VALUES(106,'위대한 사람은 목적을','소인들은 공상을 가지고 있다',NULL);
INSERT INTO "proverbs" VALUES(107,'사람의 척도는 그가 불행을 얼마나 잘 이겨내는지에 달려있다','프르다크)',NULL);
INSERT INTO "proverbs" VALUES(108,'돈으로 살 수 있는 행복이라 불리는 상품은 없다','헨리 밴 다이크)',NULL);
INSERT INTO "proverbs" VALUES(109,'세상에서 가장 아름다운 것은 세상 그 자체이다','스티븐슨)',NULL);
INSERT INTO "proverbs" VALUES(110,'일은 인간생활의 피할 수 없는 조건이며','인간 복지의 참된 근원이다',NULL);
INSERT INTO "proverbs" VALUES(111,'좋은 전쟁 또는 나쁜 평화는 없다','프랭클린)',NULL);
INSERT INTO "proverbs" VALUES(112,'일은 인류를 사로잡는 모든 질환과 비참을 치료해 주는 주요한 치료제이다','칼라일)',NULL);
INSERT INTO "proverbs" VALUES(113,'최대다수의 최대행복은 도덕과 입법의 초석이다','벤담)',NULL);
INSERT INTO "proverbs" VALUES(114,'전쟁에선 어느 편이 스스로를 승자라고 부를지라도 승리자는 없고 모두 패배자 뿐이다','챔벌린)',NULL);
INSERT INTO "proverbs" VALUES(115,'전쟁에서는 오직 한 번 죽지만 정치에서는 여러번 죽는다','처칠)',NULL);
INSERT INTO "proverbs" VALUES(116,'일을 몰고 가라. 그렇지 않으면 일이 너를 몰고 갈 것이다','프랭클린)',NULL);
INSERT INTO "proverbs" VALUES(117,'위대한 것 치고 정열이 없이 이루어진 것은 없다','에머슨)',NULL);
INSERT INTO "proverbs" VALUES(118,'인생을 해롭게 하는 비애를 버리고 명랑한 기질을 간직하라','세익스피어)',NULL);
INSERT INTO "proverbs" VALUES(119,'우유부단한 것만이 습관으로 되어 있는 사람보다 더 비참한 사람은 없다','제임스)',NULL);
INSERT INTO "proverbs" VALUES(120,'인간은 아직까지도 모든 컴퓨터중에서 가장 훌륭한 컴퓨터이다','케네디)',NULL);
INSERT INTO "proverbs" VALUES(121,'우리의 거의 모든 삶이 어리석은 호기심에 낭비되고 있다','보들레르)',NULL);
INSERT INTO "proverbs" VALUES(122,'조용한 물이 깊이 흐른다','릴리)',NULL);
INSERT INTO "proverbs" VALUES(123,'다른 사람들을 비난하려고 생각하기 전에 자기 자신을 추분이 살펴보아야 한다','몰리에르)',NULL);
INSERT INTO "proverbs" VALUES(124,'천재란 인내에 대한 위대한 자질 이외에는 아무것도 아니다','뷰퐁)',NULL);
INSERT INTO "proverbs" VALUES(125,'시간을 선택하는 것은 시간을 절약하는 것이다','베이컨)',NULL);
INSERT INTO "proverbs" VALUES(126,'친구들을 불신한다는 것은 그들에게 속은 것보다 더 수치스러운 일이다','로셔푸코)',NULL);
INSERT INTO "proverbs" VALUES(127,'맹세는 말에 지나지 않고','말은 바람에 지나지 않는다',NULL);
INSERT INTO "proverbs" VALUES(128,'어리석은 자는 수치스러운 일을 할 때에도 그것이 언제나 그의 의무라고 선포한다','버나드쇼)',NULL);
INSERT INTO "proverbs" VALUES(129,'시간을 잘 맞춘 침묵은 말보다 더 좋은 웅변이다','터퍼)',NULL);
INSERT INTO "proverbs" VALUES(130,'청년기는 대실수이다. 장년기는 투쟁이다. 그리고 노년기는 후회이다','디즈레일리)',NULL);
INSERT INTO "proverbs" VALUES(131,'절제는 모든 미덕의 진주고리를 이어주는 비단의 실이다','홀)',NULL);
INSERT INTO "proverbs" VALUES(132,'삶은 순간들의 연속이다. 한순간','한순간을 사는 것이 성공하는 겄이다',NULL);
INSERT INTO "proverbs" VALUES(133,'우리의 인내가 우리의 힘보다 더 많은 것을 성취할 것이다','버크)',NULL);
INSERT INTO "proverbs" VALUES(134,'인간은 패배하였을 때 끝나는 것이 아니다.포기 했을 때 끝나는 것이다','닉슨)',NULL);
INSERT INTO "proverbs" VALUES(135,'어느 사회에서나 유아들에게 우유를 먹이는 것보다 더 좋은 투자는 없다','처칠)',NULL);
INSERT INTO "proverbs" VALUES(136,'좋은 친구는 건강에도 좋다','시라손)',NULL);
INSERT INTO "proverbs" VALUES(137,'힘으로서 사람을 복종시키지 말고 덕으로서 사람을 복종시켜라','맹자)',NULL);
INSERT INTO "proverbs" VALUES(138,'많은 사람이 충고를 받지만','오직 현명한 자만이 충고의 덕을 본다',NULL);
INSERT INTO "proverbs" VALUES(139,'군자의 사귐은 담담함이 물과 같고','소인의 사귐은 달콤함이 단술과 같다',NULL);
INSERT INTO "proverbs" VALUES(140,'악은 선을 인식시키고 고통은 기쁨을 느끼게 한다','그리스도)',NULL);
INSERT INTO "proverbs" VALUES(141,'잔잔한 바다에서는 좋은 뱃사공이 만들어지지 않는다','영국속담)',NULL);
INSERT INTO "proverbs" VALUES(142,'확실한 벗은 불확실한 처지에 있을 때 알려진다','시세로)',NULL);
INSERT INTO "proverbs" VALUES(143,'사랑은 사람들을 치료한다. 사랑을 받는 사람','사랑을 주는 사람 할 것이 없이',NULL);
INSERT INTO "proverbs" VALUES(144,'말로하는 사랑은 쉽게 외면할수 있으나 행동으로 보여주는 사라은 저항할 수가 없다','무니햄)',NULL);
INSERT INTO "proverbs" VALUES(145,'성공적인 결혼이란 매일같이 개축해야 하는 건물과 같은 것이다','모로아)',NULL);
INSERT INTO "proverbs" VALUES(146,'사랑하고 나서 잃는 것은 전혀 사랑하지 않았던 것보다 더 낫다','테니슨)',NULL);
INSERT INTO "proverbs" VALUES(147,'소인은 특별한 것에 관심이 있고','위인은 평범한 것에 관심이 있다',NULL);
INSERT INTO "proverbs" VALUES(148,'용기는 대단히 중요하다. 근육과 같이 사용함으로써 강해진다','고든)',NULL);
INSERT INTO "proverbs" VALUES(149,'사랑하고 사랑받는 것은 태양을 양쪽에서 쪼이는 것과 같다','비스코트)',NULL);
INSERT INTO "proverbs" VALUES(150,'지성이란 그것을 갖고 있지 않는 사람에게는 보이지 않는다','쇼펜하우어)',NULL);
INSERT INTO "proverbs" VALUES(151,'분노는 바보들의 가슴속에서만 살아간다','아인슈타인)',NULL);
INSERT INTO "proverbs" VALUES(152,'너의 의무를 다하라. 그리고 나머지는 하나님께 맡겨라','코네일)',NULL);
INSERT INTO "proverbs" VALUES(153,'나의 음악은 어린 아이들과 동물들이 가장 잘 이해한다','스트라빈스키)',NULL);
INSERT INTO "proverbs" VALUES(154,'당신이 누군가를 배반한다면','당신은 또한 당신 자신을 배반하는 셈이다',NULL);
INSERT INTO "proverbs" VALUES(155,'가정은 삶의 보물상자가 되어야 한다','코르뷔제)',NULL);
INSERT INTO "proverbs" VALUES(156,'지식인은 지금까지 일어났던 일을 안다. 천재는 앞으로 일어날 일을 안다','치아디)',NULL);
INSERT INTO "proverbs" VALUES(157,'서툰 의사는 한번에 한 사람을 해치지만','서툰 교사는 130명을 해친다',NULL);
INSERT INTO "proverbs" VALUES(158,'태만이란 약한 마음을 가진 사람의 유일한 피난처이다','체스터필드)',NULL);
INSERT INTO "proverbs" VALUES(159,'권세가 인간을 교만으로 이끌어갈 때','시가 그에게 한계를 상기시켜준다',NULL);
INSERT INTO "proverbs" VALUES(160,'무거운 마음을 가지고 가벼운 시를 즐길 수 없다','베이커) 2proo',NULL);
INSERT INTO "proverbs" VALUES(161,'사악은 언제나 미덕보다 더 쉽다. 왜냐하면 사악은 모든일에 지름길을 택하기 때문이다','존스)',NULL);
INSERT INTO "proverbs" VALUES(162,'훌륭한 삶에는 세 가지 요소가 있다. 즉 배우는 일','돈 버는 일',NULL);
INSERT INTO "proverbs" VALUES(163,'패배를 극복하는 법을 배워야 한다. 그럴때에 당신의 인격이 향상된다','닉슨)',NULL);
INSERT INTO "proverbs" VALUES(164,'호기심이란 무지의 고백인데 그것은 의도적이며 당당하며 열렬하다','루빈슈타인)',NULL);
INSERT INTO "proverbs" VALUES(165,'여행이란 젊은이들에게는 교육의 일부이며 연장자들에겐 경험의 일부이다','베이컨)',NULL);
INSERT INTO "proverbs" VALUES(166,'덕이 없는 아름다움은 향기 없는 꽃이다','프랑스 격언)',NULL);
INSERT INTO "proverbs" VALUES(167,'무관심 때문에 사람은 실제로 죽기전에 죽어버린다','위젤)',NULL);
INSERT INTO "proverbs" VALUES(168,'긍지는 인간이 입을 수 있는 가장 훌륭한 갑옷이다','제롬)',NULL);
INSERT INTO "proverbs" VALUES(169,'신기한 말을 하는 것이 귀함이 아니라 실행함이 귀하다','이태백)',NULL);
INSERT INTO "proverbs" VALUES(170,'의복에만 마음이 쏠리는 것은 마음과 인격이 잠든 탓이다','에머슨)',NULL);
INSERT INTO "proverbs" VALUES(171,'누구든지 크나큰 시련을 당하기 전에는 참다운 인간이 못된다','레오랄지이)',NULL);
INSERT INTO "proverbs" VALUES(172,'위대한 사람은 모두가 겸손하다','레싱)',NULL);
INSERT INTO "proverbs" VALUES(173,'장점과 훌륭한 예의는 어디서나 번영할 것이다','체스터필드)',NULL);
INSERT INTO "proverbs" VALUES(174,'좋은 가문에서 태어나는 것은 바람직한 일이다. 그러나 그 영광은 조상의 것이다','플루타르쿠스)',NULL);
INSERT INTO "proverbs" VALUES(175,'충고자는 아무리 신랄하여도 결코 해를 끼치지 않는다','푸블릴리우스 시루스)',NULL);
INSERT INTO "proverbs" VALUES(176,'먹는 것은 자신을 즐겁게 하기 위함이요. 입는 것은 남을 즐겁게 하기 위함이다','프랭클린)',NULL);
INSERT INTO "proverbs" VALUES(177,'신사를 만드는 것은 옷이 아니다','영국속담)',NULL);
INSERT INTO "proverbs" VALUES(178,'재산가들 중에는 상식을 가진 자가 드물다','유베날리스)',NULL);
INSERT INTO "proverbs" VALUES(179,'행복이란 불만에 자기가 속지 않으면 된다','러셀)',NULL);
INSERT INTO "proverbs" VALUES(180,'진주를 간직하고 있는 것은 병든 궁이다','세드)',NULL);
INSERT INTO "proverbs" VALUES(181,'적은 것을 적다고 하지 말며 천한 것을 천하게 여기지 말라','소자)',NULL);
INSERT INTO "proverbs" VALUES(182,'인간은 사회적 동물이다','아리스토텔레스)',NULL);
INSERT INTO "proverbs" VALUES(183,'가시나무를 심는 자는 장미를 기대해서는 안된다','필페이)',NULL);
INSERT INTO "proverbs" VALUES(184,'모든 날 중 가장 완전히 잃어버린 날은 웃지 않은 날이다','샹포르)',NULL);
INSERT INTO "proverbs" VALUES(185,'근심은 세월을 거치지 않고 백발과 노령을 가져온다','영국속담)',NULL);
INSERT INTO "proverbs" VALUES(186,'권리는 어느 곳에나 도리를 벗어난 곳에서는 존재할 수 없다','파크)',NULL);
INSERT INTO "proverbs" VALUES(187,'공손과 인간성과의 관계는','따스함과 밀초와의 관계와 같다',NULL);
INSERT INTO "proverbs" VALUES(188,'이기는 것이 중요한 것이 아니다. 어떻게 노력하는가가 문제이다','쿠베르탕)',NULL);
INSERT INTO "proverbs" VALUES(189,'두사람의 개성의 만남은 두가지 화학물질의 접촉과 같다. 반응이 있으면 둘 다 변화한다','융)',NULL);
INSERT INTO "proverbs" VALUES(190,'참고 버티라. 그 고통은 차츰차츰 너에게 좋은 것으로 변할 것이다','오비디우스)',NULL);
INSERT INTO "proverbs" VALUES(191,'오래 가는 행복은 정직한 것 속에서만 발견할 수 있다','리히텐베르히)',NULL);
INSERT INTO "proverbs" VALUES(192,'넌 자신을 누구에겐가 필요한 존재로 만들라. 누구에게든 인생을 고되게 만들지 말라','에머슨)',NULL);
INSERT INTO "proverbs" VALUES(193,'종소리처럼 맑고 분명해라','레이)',NULL);
INSERT INTO "proverbs" VALUES(194,'존재하는 모든 훌륭한 것은 독창력의 열매이다','밀)',NULL);
INSERT INTO "proverbs" VALUES(195,'인내는 쓰다. 그러나 그 열매는 달다','루소)',NULL);
INSERT INTO "proverbs" VALUES(196,'훌륭한 말은 훌륭한 무기이다','풀러)',NULL);
INSERT INTO "proverbs" VALUES(197,'어린이가 없는 곳에 천국은 없다','스윈번)',NULL);
INSERT INTO "proverbs" VALUES(198,'"말하자마자 행동하는 사람','그것이 가치있는 사람이다',NULL);
INSERT INTO "proverbs" VALUES(199,'대화시의 신중은 웅변보다 더 중요하다','그라시안)',NULL);
INSERT INTO "proverbs" VALUES(200,'양심은 어떠한 과학의 힘보다도 강하고 현명하다','라데이러)',NULL);
INSERT INTO "proverbs" VALUES(201,'어리석은 짓을 삼가는 것이 지혜의 입문이다','호라티우스)',NULL);
INSERT INTO "proverbs" VALUES(202,'교육의 목표는 지식의 증진과 진리의 씨부리기이다','케네디)',NULL);
INSERT INTO "proverbs" VALUES(203,'미소','악수',NULL);
INSERT INTO "proverbs" VALUES(204,'아예 배우지 않느니 보다는 늦으나마 배우는 편이 낫다','클레오 불루스)',NULL);
INSERT INTO "proverbs" VALUES(205,'생명이 있는 한','사람은 무었인가 바랄수 있다',NULL);
INSERT INTO "proverbs" VALUES(206,'자기 일을 멸시하는 자는 먹을 양식과 싸운다','스퍼전)',NULL);
INSERT INTO "proverbs" VALUES(207,'습관은 제二의 천성으로 제一의 천성을 파괴한다','파스칼)',NULL);
INSERT INTO "proverbs" VALUES(208,'사람의 천성과 직업이 맞을때 행복하다','베이컨)',NULL);
INSERT INTO "proverbs" VALUES(209,'사람은 돈지갑은 가난해도','정신적으로는 긍지를 가질 수 있다',NULL);
INSERT INTO "proverbs" VALUES(210,'한나라의 진정한 재산은 땀흘려 일하는 부지런한 주민의 수에 있다','나폴레옹)',NULL);
INSERT INTO "proverbs" VALUES(211,'사랑은 인생의 소금이다','셰필드)',NULL);
INSERT INTO "proverbs" VALUES(212,'시련이란 진리로 통하는 으뜸가는 길이다','바이런)',NULL);
INSERT INTO "proverbs" VALUES(213,'사랑없이 사는 것은 정말로 사는 것이 아니다','몰리에르)',NULL);
INSERT INTO "proverbs" VALUES(214,'얼마나 오래 사느냐가 아니라 어떻게 사느냐가 문제(베일리)','$1',NULL);
INSERT INTO "proverbs" VALUES(215,'내기는 탐욕의 아들이며','부정의 형제이며',NULL);
INSERT INTO "proverbs" VALUES(216,'자신의 주인이 되는 자는 곧 다른 사람들의 주인이 될 것이다','풀러)',NULL);
INSERT INTO "proverbs" VALUES(217,'희망은 가난한 인간의 빵이다','탈레스)',NULL);
INSERT INTO "proverbs" VALUES(218,'빈부강약을 막론하고 일하지 않는자를 배척하라','루소)',NULL);
INSERT INTO "proverbs" VALUES(219,'시간을 이용할줄 아는 사람은 하루를 사흘로 통용한다','영국속담)',NULL);
INSERT INTO "proverbs" VALUES(220,'모든 일은 어려운 고비를 넘겨야 쉬워진다','풀러)',NULL);
INSERT INTO "proverbs" VALUES(221,'우리는 지성적으로 되기 위해 많은 대가를 치른다','에우리피데스)',NULL);
INSERT INTO "proverbs" VALUES(222,'정신으로 창조된 것은 물질보다 한결 생명적이다','보들레르)',NULL);
INSERT INTO "proverbs" VALUES(223,'검약은 훌륭한 소득이다','에라스무스)',NULL);
INSERT INTO "proverbs" VALUES(224,'지혜는 고통을 통해서 생긴다','아에스킬루스)',NULL);
INSERT INTO "proverbs" VALUES(225,'좋은 나무는 좋은 열매를 맺는다','랭런드)',NULL);
INSERT INTO "proverbs" VALUES(226,'말도 행동이고 행동도 말의 일종이다','에머슨)',NULL);
INSERT INTO "proverbs" VALUES(227,'중간이 가장 안전할 것이다','오비디우스)',NULL);
INSERT INTO "proverbs" VALUES(228,'행동에 부주의하지 말며','말에 혼동되지 말며',NULL);
INSERT INTO "proverbs" VALUES(229,'모든 개량과 진보의 근본은 근로이다','카네기)',NULL);
INSERT INTO "proverbs" VALUES(230,'충고는 좀처럼 환영받지 못한다','체스터필드)',NULL);
INSERT INTO "proverbs" VALUES(231,'탐구정신은 우리가 살고 있는 시대의 위대한 특징이다','풀)',NULL);
INSERT INTO "proverbs" VALUES(232,'지구상에는 인간이외는 위대한 것이 없다.인간에게는 지성이외엔 훌륭한 것이 없다','헤밀턴)',NULL);
INSERT INTO "proverbs" VALUES(233,'험한 언덕을 오르려면 처음에는 서서희 걸어야 한다','세익스피어)',NULL);
INSERT INTO "proverbs" VALUES(234,'논리와 상식은 다르다','하버드)',NULL);
INSERT INTO "proverbs" VALUES(235,'많은 사물중에서 가운데가 제일이다.내 위치도 가운데가 되게 하라','포킬리데스)',NULL);
INSERT INTO "proverbs" VALUES(236,'자기 자신을 예찬하는 자는 신의 미움을 받는다','클레멘스)',NULL);
INSERT INTO "proverbs" VALUES(237,'악은 선을 인식시키고 고통은 기쁨을 느끼게 한다','그리스도)',NULL);
INSERT INTO "proverbs" VALUES(238,'마땅히 행할 길을 아이에게 가르쳐라.그리하면 늙으도 그것을 떠나지 않으리라','성경)',NULL);
INSERT INTO "proverbs" VALUES(239,'근심은 미를 훔치는 도둑이다','마미언)',NULL);
INSERT INTO "proverbs" VALUES(240,'한치의 기쁨마다 한자의 고민이 있다','베넘)',NULL);
INSERT INTO "proverbs" VALUES(241,'인간은 환경을 창조하고 환경은 인간을 창조한다','밝은 사회)',NULL);
INSERT INTO "proverbs" VALUES(242,'아름다운 것은 선하고 선한 자는 곧 아름다워진다','삽포)',NULL);
INSERT INTO "proverbs" VALUES(243,'공정하고 바른데는 근거를 두었다면 긍지보다 이익을 주는 것은 좀처럼 없다','밀턴)',NULL);
INSERT INTO "proverbs" VALUES(244,'시간은 언제까지든 당신을 기다리는 것은 아니다','짐멜)',NULL);
INSERT INTO "proverbs" VALUES(245,'인생은 불확실한 항해이다','셰익스피어)',NULL);
INSERT INTO "proverbs" VALUES(246,'아름다움이란 경솔한 사람이 그릇생각하듯 보이는 그대로 외관만의 치레는 아니다','스펜스)',NULL);
INSERT INTO "proverbs" VALUES(247,'창조는 고민속에서 나오고 발전은 고생 속에서 움튼다','밝은 사회)',NULL);
INSERT INTO "proverbs" VALUES(248,'소비된 시간은 존재하고 이용된 시간은 생명이다','영)',NULL);
INSERT INTO "proverbs" VALUES(249,'내가 아직 살아있는 동안에는 나로 하여금 헛되이 살지 않게 하라','에디슨)',NULL);
INSERT INTO "proverbs" VALUES(250,'정직한 노동은 사랑스런 얼굴을 낳는다','대커)',NULL);
INSERT INTO "proverbs" VALUES(251,'인간은 이성적 동물이다','세네카)2proo.net',NULL);
INSERT INTO "proverbs" VALUES(252,'모범은 모든 사람이 읽을 수 있는 교훈이다','웨스트)',NULL);
INSERT INTO "proverbs" VALUES(253,'일은 시작할 때가 언제나 가장 좋다','파스칼)',NULL);
INSERT INTO "proverbs" VALUES(254,'인류의 목적은 휴식이 아니다.그것은 지적이며 도덕적인 완성이다','르낭)',NULL);
INSERT INTO "proverbs" VALUES(255,'공손이란 가장 친절한 방법으로 가장 친절한 것을 향하고 말하는 것이다','루이전)',NULL);
INSERT INTO "proverbs" VALUES(256,'행실은 각자가 자기의 이미지를 보여주는 거울이다','괴테)',NULL);
INSERT INTO "proverbs" VALUES(257,'다른 사람을 지배하려는 사람은','먼저 자기 자신의 주인이 되어야 한다',NULL);
INSERT INTO "proverbs" VALUES(258,'위대한 것을 멸시하고','과도함 보다는 중용을 택하는 것이 군자의 특징이다',NULL);
INSERT INTO "proverbs" VALUES(259,'목적 없이 존재하는 것은 아무 것도 없다','보들레르)',NULL);
INSERT INTO "proverbs" VALUES(260,'전력을 다해서 시간에 대항하라','톨스토이)',NULL);
INSERT INTO "proverbs" VALUES(261,'인생에서 중요한 법칙은 만사에 중용을 지키는 일이다','테렌티우스)',NULL);
INSERT INTO "proverbs" VALUES(262,'다정하고 조용한 말은 힘이 있다','에머슨)',NULL);
INSERT INTO "proverbs" VALUES(263,'돈이 있어도 이상이 없는 사람은 몰락의 길을 밟는다','도스도예프스키)',NULL);
INSERT INTO "proverbs" VALUES(264,'마음의 즐거움은 얼굴을 빛나게 하여도 마음의 근심은 심령을 상하게 하느니라','성경)',NULL);
INSERT INTO "proverbs" VALUES(265,'평온한 마음으로 아껴 생활하는 것이 사람에게 큰 부이다','루크레티우스)',NULL);
INSERT INTO "proverbs" VALUES(266,'버들가지는 약하나 다른 재목을 묵는다','허버트)',NULL);
INSERT INTO "proverbs" VALUES(267,'사람의 잘못은 좀처럼 자신에게는 나타나지 않는다','셰익스피어)',NULL);
INSERT INTO "proverbs" VALUES(268,'부당한 이득을 얻지말라.그것은 손해와 같은 것이다','헤시오도스)',NULL);
INSERT INTO "proverbs" VALUES(269,'근로가 잠들면 빈곤은 창으로 들어온다','라이닉)',NULL);
INSERT INTO "proverbs" VALUES(270,'자기가 할 수 있는 일은 남에게 밀지 말라','제퍼슨)',NULL);
INSERT INTO "proverbs" VALUES(271,'최초의 큰 웃음보다는 마지막의 미소가 오히려 났다','영국속담)',NULL);
INSERT INTO "proverbs" VALUES(272,'쓴 맛을 보기 전에 단 맛을 보아서는 안된다','고울딤 헴)',NULL);
INSERT INTO "proverbs" VALUES(273,'조금 알기 위해서 많이 공부해야 한다','몽테스키외)',NULL);
INSERT INTO "proverbs" VALUES(274,'인생의 참된 목적은 영원히 생명을 깨닫는데 있다','톨스토이)',NULL);
INSERT INTO "proverbs" VALUES(275,'상식은 그렇게 흔한 것이 아니다','볼테르)',NULL);
INSERT INTO "proverbs" VALUES(276,'훌륭한 충고보다 값진 선물은 없다','에라스무스)',NULL);
INSERT INTO "proverbs" VALUES(277,'사자라 할지라도 파리들로 부터 자기 몸을 방어해야 한다','독일격언)',NULL);
INSERT INTO "proverbs" VALUES(278,'내 자신의 무식을 아는 것은 지식에로의 첫걸음이다','바이런) http://2proo.net',NULL);
INSERT INTO "proverbs" VALUES(279,'가장 훌륭한 예언은 상식','즉 우리의 원래의 지혜이다',NULL);
INSERT INTO "proverbs" VALUES(280,'행복하게 산다는 것은 마음의 평온함을 뜻한다','시세로)',NULL);
INSERT INTO "proverbs" VALUES(281,'자기 자신을 아는 것은 참된 진보이다','안데르센)',NULL);
INSERT INTO "proverbs" VALUES(282,'배우라.비교하라.사실을 수입하라','파플로프)',NULL);
INSERT INTO "proverbs" VALUES(283,'할 수 있는 한 훌륭한 인생을 만들라.인생은 짧고 곧 지나간다','오울디즈)',NULL);
INSERT INTO "proverbs" VALUES(284,'군자는 기회가 없다고 불평하지 않는다','에머슨)',NULL);
INSERT INTO "proverbs" VALUES(285,'두 사람의 머리는 한 사람의 머리보다 낫다','헤이우드)',NULL);
INSERT INTO "proverbs" VALUES(286,'탐구하여 찾아질 수 없을 정도로 어려운 문제는 존재하지 않는다','티랜티우스)',NULL);
INSERT INTO "proverbs" VALUES(287,'인간은 천에 따라서 자기 옷을 지어야 한다','내쉬)',NULL);
INSERT INTO "proverbs" VALUES(288,'아이들에게는 비평보다도 귀감이 필요하다','쥬벨)',NULL);
INSERT INTO "proverbs" VALUES(289,'큰 나무는 바람을 많이 받는다','카네기)',NULL);
INSERT INTO "proverbs" VALUES(290,'담화는 마음의 보다 즐거운 향연이다','호메로스)',NULL);
INSERT INTO "proverbs" VALUES(291,'천재응 1퍼센트의 영감이요. 99퍼센트는 노력이다','보비)',NULL);
INSERT INTO "proverbs" VALUES(292,'뿌리가 튼튼해야 열매가 많다','용비어천가)',NULL);
INSERT INTO "proverbs" VALUES(293,'서투런 의사소통은','훌륭한 예절을 망쳐버린다',NULL);
INSERT INTO "proverbs" VALUES(294,'마음이 어진 사람은 조그마한 집에 살아도 행복하다','홍자성)',NULL);
INSERT INTO "proverbs" VALUES(295,'일의 기량을 닦기 위해서 가장 중요한 것은 실행과 경험이다','콜루맬라)',NULL);
INSERT INTO "proverbs" VALUES(296,'산 기계를 만들지 말고','인간을 만들라',NULL);
INSERT INTO "proverbs" VALUES(297,'다른 인간을 증오하는 댓가는','자신을 더 적게 사랑하는 것이다',NULL);
INSERT INTO "proverbs" VALUES(298,'깨끗한 의복은 좋은 소개장(영국속담)2proo.net','$1',NULL);
INSERT INTO "proverbs" VALUES(299,'안심하면서 먹는 한조각 빵이 근심하면서 먹는 잔치보다 낫다','이솝)',NULL);
INSERT INTO "proverbs" VALUES(300,'격언','격언 모음',NULL);
INSERT INTO "proverbs" VALUES(301,'명언 모음','격언 모음',NULL);
INSERT INTO "proverbs" VALUES(302,'나는 나 자신을 빼 놓고는 모두 안다','비용)',NULL);
INSERT INTO "proverbs" VALUES(303,'강한 사람이란 가장 훌륭하게 고독을 견디어 낸 사람이다','쉴러)',NULL);
INSERT INTO "proverbs" VALUES(304,'만약 급히 서두르려면 돌아 가는 길로 가라','영국속담)',NULL);
INSERT INTO "proverbs" VALUES(305,'덕이 없는 아름다움은 향기 없는 꽃이다','프랑스 격언)',NULL);
INSERT INTO "proverbs" VALUES(306,'인간성 이외에는 본질적으로 진실한 것은 없다','콩트) http://2proo.net',NULL);
INSERT INTO "proverbs" VALUES(307,'화가 나면 열을 세어라. 풀리지 않는 다면 백을 세어라','제퍼슨)',NULL);
INSERT INTO "proverbs" VALUES(308,'날이 밝기 직전에 항상 가장 어둡다','풀러)',NULL);
INSERT INTO "proverbs" VALUES(309,'미련한 자는 자기 행위를 바른 줄로 여긴다','성경)',NULL);
INSERT INTO "proverbs" VALUES(310,'모든 국가의 기초는 그 나라 젊은 이들의 교육이다','디오게네스)',NULL);
INSERT INTO "proverbs" VALUES(311,'인간은 신의 걸작품이다','퀼즈)',NULL);
INSERT INTO "proverbs" VALUES(312,'인간은 죽을 때까지 완전한 인간이 못된다','플랭클린)',NULL);
INSERT INTO "proverbs" VALUES(313,'자기가 가고 있는 곳을 모르는 사람은 결코 높이 향상하지 못한다','크롬웰)',NULL);
INSERT INTO "proverbs" VALUES(314,'진정한 벗은 제2의 자기인 것이다','아리스토텔레스)',NULL);
INSERT INTO "proverbs" VALUES(315,'자신을 알 수 있는 사람이야말로 진정한 현인이다','초서)',NULL);
INSERT INTO "proverbs" VALUES(316,'시기와 질투는 언제나 남을 쏘려다가 자신을 쏜다','맹자)',NULL);
INSERT INTO "proverbs" VALUES(317,'진정한 위인치고 자신을 위인으로 생각하는 자는 없다','해즐리트)',NULL);
INSERT INTO "proverbs" VALUES(318,'폭풍은 참나무가 더욱 뿌리를 깊게 박도록 한다','허버트)',NULL);
INSERT INTO "proverbs" VALUES(319,'모범은 훈화보다 유효하다','영국속담)',NULL);
INSERT INTO "proverbs" VALUES(320,'즐거움에 찬 얼굴은 한접시의 물로도 연회를 만들 수 있다','허버트)',NULL);
INSERT INTO "proverbs" VALUES(321,'대화는 학생들의 실험실이요','작업장이다',NULL);
INSERT INTO "proverbs" VALUES(322,'미지를 향해 출발하는 사람은 누구나 외로운 모험에 만족해야 한다','지드)',NULL);
INSERT INTO "proverbs" VALUES(323,'노동은 생명이요','광명이다',NULL);
INSERT INTO "proverbs" VALUES(324,'기와 한장 아껴서 대들보 썩는다','한국속담)',NULL);
INSERT INTO "proverbs" VALUES(325,'소인은 특별한 것에 관심이 있고','위인은 평범한 것에 관심이 있다',NULL);
INSERT INTO "proverbs" VALUES(326,'하나의 작은 꽃을 만드는 데도 오랜 세월의 노력이 필요하다','블레이크)',NULL);
INSERT INTO "proverbs" VALUES(327,'인간은 교육을 통하지 않고는 인간이 될 수 없는 유일한 존재이다','칸트)',NULL);
INSERT INTO "proverbs" VALUES(328,'노년은 청춘에 못지 않은 좋은 기회이다','롱펠로우)',NULL);
INSERT INTO "proverbs" VALUES(329,'한 손으로 다른 손을 씻고','두 손으로 얼굴을 씻는다',NULL);
INSERT INTO "proverbs" VALUES(330,'우리의 거의 모든 삶이 어리석은 호기심에 낭비되고 있다','보들레르)',NULL);
INSERT INTO "proverbs" VALUES(331,'풍랑은 항상 능력있는 항해자 편이다','기번)',NULL);
INSERT INTO "proverbs" VALUES(332,'말 한 마디가 세계를 지배한다','쿠크)',NULL);
INSERT INTO "proverbs" VALUES(333,'우리들은 감탄과 희망과 사랑으로 산다','워즈워드)',NULL);
INSERT INTO "proverbs" VALUES(334,'단 하나의 하늘에 올려진 고마워하는 생각이 완전한 기도이다','레싱)',NULL);
INSERT INTO "proverbs" VALUES(335,'말만 하고 행동하지 않는 사람은 잡초로 가득 찬 정원과 같다','하우얼)',NULL);
INSERT INTO "proverbs" VALUES(336,'지식이 깊은 사람은 시간의 손실을 가장 슬퍼한다','단테)',NULL);
INSERT INTO "proverbs" VALUES(337,'미는 내부의 생명으로부터 나오는 빛이다','켈러)',NULL);
INSERT INTO "proverbs" VALUES(338,'자신이 자신의 지휘관이다','플라우투스)',NULL);
INSERT INTO "proverbs" VALUES(339,'오늘 가장 좋게 웃는 자는 역시 최후에도 웃을 것이다','니체)',NULL);
INSERT INTO "proverbs" VALUES(340,'영혼이 깃든 청춘은 그렇게 쉽사리 사라지지 않는다','카로사)',NULL);
INSERT INTO "proverbs" VALUES(341,'노령에 활기를 주는 진정한 방법은','마음의 청춘을 연장하는 것이다',NULL);
INSERT INTO "proverbs" VALUES(342,'결백한 자와 미인은','시간 이외에는 적이 없다',NULL);
INSERT INTO "proverbs" VALUES(343,'너의 위대한 조상을 본받아 행동하라','드라이든)',NULL);
INSERT INTO "proverbs" VALUES(344,'지혜의 가장 명백한 징조는 쉴새없이 명랑한 것이다','몽테뉴)2proo',NULL);
INSERT INTO "proverbs" VALUES(345,'아름다운 것！ 그것은 마음의 눈으로 보여지는 미(美)이다','주베르)',NULL);
INSERT INTO "proverbs" VALUES(346,'많은 사람이 충고를 받지만','오직 현명한 자만이 충고의 덕을 본다',NULL);
INSERT INTO "proverbs" VALUES(347,'정당하게 사는 자에게는 어느 곳이든 안전하다','에픽테투스)',NULL);
INSERT INTO "proverbs" VALUES(348,'지혜는 간혹 누더기 가면을 덮어쓰고 있다','스타티우스)',NULL);
INSERT INTO "proverbs" VALUES(349,'창조적인 예술가는 그 전의 작품에 만족하지 않기 때문에 다음 작품을 만든다','쇼스타코비치)',NULL);
INSERT INTO "proverbs" VALUES(350,'위기의 시기에는 가장 대담한 방법이 때로는 가장 안전하다','키신저)',NULL);
INSERT INTO "proverbs" VALUES(351,' 부자 옆에 줄을 서라. 산삼밭에 가야 산삼을 캘 수 있다.','$1',NULL);
INSERT INTO "proverbs" VALUES(352,'부자처럼 생각하고 부자처럼 행동하라. 나도 모르는 사이에 부자 가 되어 있다.','$1',NULL);
INSERT INTO "proverbs" VALUES(353,'항상 기뻐하라. 그래야 기뻐할 일이 줄줄이 따라온다.','$1',NULL);
INSERT INTO "proverbs" VALUES(354,'남의 잘됨을 축복하라.  그 축복이 메아리처럼 나를 향해 돌아온다.','$1',NULL);
INSERT INTO "proverbs" VALUES(355,'써야할 곳','안 써도 좋을 곳을 분간하라.   판단이 흐리면 낭패가 따른다.',NULL);
INSERT INTO "proverbs" VALUES(356,' 자꾸 막히는 것은 우선 멈춤 신호이다.   멈춘 다음 정비하고 출발하라.','$1',NULL);
INSERT INTO "proverbs" VALUES(357,' 힘들어도 웃어라. 절대자도 웃는 사람을 좋아한다.','$1',NULL);
INSERT INTO "proverbs" VALUES(358,' 들어온 떡만 먹으려 말라. 떡이 없으면 나가서 만들어라.','$1',NULL);
INSERT INTO "proverbs" VALUES(359,' 기도하고 행동하라. 기도와 행동은 앞바퀴와 뒷바퀴이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(360,' 자신의 영혼을 위해 투자하라.    투명한 영혼은 천년 앞을 내다본다.','$1',NULL);
INSERT INTO "proverbs" VALUES(361,' 마음의 무게를 가볍게 하라. 마음이 무거우면 세상이 무겁다.','$1',NULL);
INSERT INTO "proverbs" VALUES(362,' 돈은 거짓말을 하지 않는다. 돈 앞 에서 진실하라.','$1',NULL);
INSERT INTO "proverbs" VALUES(363,' 씨 돈은 쓰지 말고 아껴두어라.    씨 돈은 새끼를 치는 종자돈이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(364,' 샘물은 퍼낼수록 맑은 물이 솟아난다. 아낌없이 베풀어라.','$1',NULL);
INSERT INTO "proverbs" VALUES(365,' 헌 돈은 새 돈으로 바꿔 사용하라. 새 돈은 충성심을 보여준다.','$1',NULL);
INSERT INTO "proverbs" VALUES(366,' 적극적인 언어를 사용하라.    부정적인 언어는 복 나가는 언어이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(367,' 깨진 독에 물을 붓지 말라.    새는 구멍을 막은 다음 물을 부어라.','$1',NULL);
INSERT INTO "proverbs" VALUES(368,' 요행의 유혹에 넘어가지 말라. 요행은 불행의 안내자이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(369,' 자신감을 높여라 기가 살아야 운이 산다.','$1',NULL);
INSERT INTO "proverbs" VALUES(370,' 검약에 앞장서라. 약 중에 제일 좋은 약은 검약이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(371,' 장사꾼이 되지 말라. 경영자가 되면 보는 것이 다르다.','$1',NULL);
INSERT INTO "proverbs" VALUES(372,' 서두르지 말라. 급히 먹은 밥은 채하기 마련이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(373,' 세상에 우연은 없다. 한번 맺은 인연을 소중히 하라.','$1',NULL);
INSERT INTO "proverbs" VALUES(374,' 돈 많은 사람을 부러워 말라. 그가 사는 법을 배우도록 하라.','$1',NULL);
INSERT INTO "proverbs" VALUES(375,' 본전 생각을 하지 말라. 손해가 이익을 끌고 온다.','$1',NULL);
INSERT INTO "proverbs" VALUES(376,'돈을 내 맘대로 쓰지 말라. 돈에게 물어보고 사용하라.','$1',NULL);
INSERT INTO "proverbs" VALUES(377,' 느낌을 소중히 하라. 느낌은 신의 목소리이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(378,' 돈을 애인처럼 사랑하라. 사랑은 기적을 보여준다.','$1',NULL);
INSERT INTO "proverbs" VALUES(379,' 기회는 눈 깜빡하는 사이에 지나간다. 순발력을 키우라.','$1',NULL);
INSERT INTO "proverbs" VALUES(380,' 말이 씨앗이다. 좋은 종자를 심어라.','$1',NULL);
INSERT INTO "proverbs" VALUES(381,' 작은 것 탐내다가 큰것을 잃는다.    무엇이 큰 것인지를 판단하라.','$1',NULL);
INSERT INTO "proverbs" VALUES(382,' 돌다리만 두드리지 말라. 그 사이에 남들은 결승점에 가 있다.','$1',NULL);
INSERT INTO "proverbs" VALUES(383,' 돈의 노예로 살지 말라. 돈의 주인으로 기쁘게 살아라.','$1',NULL);
INSERT INTO "proverbs" VALUES(384,' 절망 속에서도 희망을 잃지 말라. 희망만이 희망을 키운다.','$1',NULL);
INSERT INTO "proverbs" VALUES(385,' 불경기에도 돈은 살아서 숨쉰다. 돈의 숨소리에 귀를 기울여라.','$1',NULL);
INSERT INTO "proverbs" VALUES(386,' 인색하지 말라. 인색한 사람에게는 돈도 야박하게 대한다.','$1',NULL);
INSERT INTO "proverbs" VALUES(387,' 더운밥 찬밥 가리지 말라.    뱃속에 들어가면 찬밥도 더운 밥이 된다.','$1',NULL);
INSERT INTO "proverbs" VALUES(388,' 좋은 만남이 좋은 운을 만든다. 좋은 인연을 소중히 생각하라.','$1',NULL);
INSERT INTO "proverbs" VALUES(389,' 효도하고 또 효도하라. 그래야 하늘과 조상이 돕는다.','$1',NULL);
INSERT INTO "proverbs" VALUES(390,' 있을 때 겸손하라. 그러나 없을 때는 당당하라.','$1',NULL);
INSERT INTO "proverbs" VALUES(391,' 한발만 앞서라. 모든 승부는 한발자국 차이이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(392,' 돈은 돈을 좋아한다. 생기는 즉시 입금시켜라.','$1',NULL);
INSERT INTO "proverbs" VALUES(393,' 티끌 모아 태산이 된다. 작은 돈에도 감사하라.','$1',NULL);
INSERT INTO "proverbs" VALUES(394,' 마음이 가난하면 가난을 못 벗는다. 마음에 풍요를 심어라.','$1',NULL);
INSERT INTO "proverbs" VALUES(395,' 돈이 가는 길은 따로 있다. 그 길목을 지키며 미소를 지어라.','$1',NULL);
INSERT INTO "proverbs" VALUES(396,' 처자식 빼고 다 바꿔라!','$1',NULL);
INSERT INTO "proverbs" VALUES(397,' 천재 한명이 10만명을 먹여 살린다.','$1',NULL);
INSERT INTO "proverbs" VALUES(398,' 중국은 쫓아오고 일본은 앞서가고','한국은 샌드위치 상황.    샌드위치 벗어나려면 인재 양성하라.',NULL);
INSERT INTO "proverbs" VALUES(399,'자체적으로 키우고 외국에서 스카우트해서라도 인재를 양성하라','$1',NULL);
INSERT INTO "proverbs" VALUES(400,'오늘의 하나는 내일의 둘의 가치가 있다.-B.프랭크린','$1',NULL);
INSERT INTO "proverbs" VALUES(401,'세상에서 가장 용감한 광경은 불리한 여건과 싸우는 사람이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(402,'미래를 생각지 않는다면 아무것도 가질 수 없다.-J. 골즈워디','$1',NULL);
INSERT INTO "proverbs" VALUES(403,'미래는 현재에 의해 얻어진다.','$1',NULL);
INSERT INTO "proverbs" VALUES(404,'오늘은 어제의 시작이다.-T.풀러','$1',NULL);
INSERT INTO "proverbs" VALUES(405,'쾌락은 일시적이고 명예는 불멸이다.-페라언데르 디오게네스','$1',NULL);
INSERT INTO "proverbs" VALUES(406,'의무란 우리 언어중 가장 훌륭한 단어이다.-R.리','$1',NULL);
INSERT INTO "proverbs" VALUES(407,'승리는 의지의 산물이다. -F.포시장군','$1',NULL);
INSERT INTO "proverbs" VALUES(408,'책임을 다른 사람들과 나누어 가질 수 없다. -A. 브라운','$1',NULL);
INSERT INTO "proverbs" VALUES(409,'책임은 돈으로 살 수 없다. -P.F.드러커','$1',NULL);
INSERT INTO "proverbs" VALUES(410,'수고가 많지 않은 자에게 인생은 혜택을 베풀지 않는다.-호라티우스','$1',NULL);
INSERT INTO "proverbs" VALUES(411,'질질 끄는 사람은 하상 파멸로 몸부림친다.-헤시오도스','$1',NULL);
INSERT INTO "proverbs" VALUES(412,'일은 모든것을 정복한다. -베르질리우스','$1',NULL);
INSERT INTO "proverbs" VALUES(413,'일이라는 것은 정직한 것이기 때문에 결과는 정직하게 대답해준다.','$1',NULL);
INSERT INTO "proverbs" VALUES(414,'천재는 근면으로 길러진다. -키케로','$1',NULL);
INSERT INTO "proverbs" VALUES(415,'자기 일을 찾는 자는 복이 있다. - T.칼리일','$1',NULL);
INSERT INTO "proverbs" VALUES(416,'무슨 일이든 익숙해지면 아무것도 아지다. -J.스위프트','$1',NULL);
INSERT INTO "proverbs" VALUES(417,'숙련은 힘보다 더 강하다. -W.G. 베넘','$1',NULL);
INSERT INTO "proverbs" VALUES(418,'끝이 좋으면 모두 좋을 것이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(419,'쉬운일은 어려운 듯이 어려운 일은 쉬운 듯이 하라. -B.그라시안','$1',NULL);
INSERT INTO "proverbs" VALUES(420,'어제는 되돌이킬 수 없는 우리의 것이 아니지만내일은 이기거나 질 수 있는 우리의 것이다. -L.B.존슨','$1',NULL);
INSERT INTO "proverbs" VALUES(421,'슬플때 명언 격언','$1',NULL);
INSERT INTO "proverbs" VALUES(422,'슬플때 필요한 격언 명언','$1',NULL);
INSERT INTO "proverbs" VALUES(423,'가장 큰 슬픔은 우리 자신으로 부터 야기되는 것이다. - 소포클레스','$1',NULL);
INSERT INTO "proverbs" VALUES(424,'시간이 덜어주지 않는 슬픔은 없다. -세르비우스 수풀리키우스키케로','$1',NULL);
INSERT INTO "proverbs" VALUES(425,'외로운 나무는 어쨌든 자라기만 한다면 강하게 자란다. -W.처칠경','$1',NULL);
INSERT INTO "proverbs" VALUES(426,'가장 오래가는 슬픔이라도 마침내는 탈출구를 찾는다.','$1',NULL);
INSERT INTO "proverbs" VALUES(427,'슬픔은 지식이다. -C.H.스퍼전','$1',NULL);
INSERT INTO "proverbs" VALUES(428,'슬픔은 그 자체가 약이다. -W.쿠퍼','$1',NULL);
INSERT INTO "proverbs" VALUES(429,'억눌린 슬픔은 질식한다. -오비디우스','$1',NULL);
INSERT INTO "proverbs" VALUES(430,'슬픔의 홍수는 더 불어날 수 없을 때 줄어든다. -베이컨','$1',NULL);
INSERT INTO "proverbs" VALUES(431,'슬픔의 유일한 치료법은 행동이다. - G.H.류이스','$1',NULL);
INSERT INTO "proverbs" VALUES(432,'밤은 별을 가져다 주듯 슬픔은 진리를 깨우쳐 준다. - P.J.베일리','$1',NULL);
INSERT INTO "proverbs" VALUES(433,'슬픈 마음이여 침착하고 탄식을 멈추라.구름 뒤엔 아직도 햇빛이 빛나고 있다. -롱페로우','$1',NULL);
INSERT INTO "proverbs" VALUES(434,'슬픔은 우리 인간의 불행한 특권이다. 우리에게 흘리기 쉬운 눈물을 준 신들은 눈물을 흘리는 더 많은 원인을 주었다.','$1',NULL);
INSERT INTO "proverbs" VALUES(435,'-W.호이트 헤드','$1',NULL);
INSERT INTO "proverbs" VALUES(436,'기쁨은 거품과 같다. -기쁨을 이루는 것이 또한 기쁨을 찢는다. -P.J.베일리','$1',NULL);
INSERT INTO "proverbs" VALUES(437,'우리는 남의 기쁨에서 자신의 슬픔을 뽑아오고  같은 식으로 남의 슬픔 에서 우리의 기쁨을 얻어온다. - O. 펠덤','$1',NULL);
INSERT INTO "proverbs" VALUES(438,'슬픔은 일순의 고통이다. 슬픔에 잠김은 인갱의 가장 큰 실수이다. cc-B.디즈레일리','$1',NULL);
INSERT INTO "proverbs" VALUES(439,'가엽게도 인간은 본래 그 바탕이 몹시 번민하며 슬퍼하하도록 마련되어 있기에 기쁨을 받아들일 소질은 빈약하다.','$1',NULL);
INSERT INTO "proverbs" VALUES(440,'불행할때 명언','$1',NULL);
INSERT INTO "proverbs" VALUES(441,'불행할때 필요한 명언 격언','$1',NULL);
INSERT INTO "proverbs" VALUES(442,'모든 면에서 행복한 것은 없다. - 호라티우스','$1',NULL);
INSERT INTO "proverbs" VALUES(443,'네가 행복하기를 원하면 즐거워 하기를 배워라. -M.프라이어','$1',NULL);
INSERT INTO "proverbs" VALUES(444,'우리는 모두 행복하기 위해 태어났다. -A.스트로우','$1',NULL);
INSERT INTO "proverbs" VALUES(445,'가장 행복한 삶은 가장 재밌는 생각을 하는 삶이다.-T.드와이트','$1',NULL);
INSERT INTO "proverbs" VALUES(446,'인생의 최고 행복은 우리가 사랑받고 있다는 확신이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(447,'장님 날에서는 애꾸가 복된 자 이다. - 프레데리크 대왕','$1',NULL);
INSERT INTO "proverbs" VALUES(448,'스스로 불행하다고 생각하는 자는 불행하다. -세네카 2proo','$1',NULL);
INSERT INTO "proverbs" VALUES(449,'모든 삶의 행복은 다른삶의 불행 위에 세워진다. -I.투르게네프','$1',NULL);
INSERT INTO "proverbs" VALUES(450,'오늘은 항상 어제와 다르다. -A.스미드','$1',NULL);
INSERT INTO "proverbs" VALUES(451,'행복해지려고 하는 마음의 소유자는 틀림없이 위대하다. -영','$1',NULL);
INSERT INTO "proverbs" VALUES(452,'불행할 때 행복했던 과거를 회상라는 것보다 더 큰 슬픔은 없다. -단테','$1',NULL);
INSERT INTO "proverbs" VALUES(453,'행복하다고 믿어야 한다. 그렇지 않으면 행복은 결코 오지 않는다.-D.맬러크','$1',NULL);
INSERT INTO "proverbs" VALUES(454,'행복은 항상 그대가 손에 잡고 있는 동안에는 작게 보잊만 놓쳐보라 그러면 곧 그것이 얼마나 크고 뉘중한가를 알 것이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(455,'- M.고리키','$1',NULL);
INSERT INTO "proverbs" VALUES(456,'무엇이 행복을 가져오를 말하기란 꽤 어렵다.빈곤도 부유도 행복을 가져오진 못했다. -K.하버드','$1',NULL);
INSERT INTO "proverbs" VALUES(457,'어려울때 필요한 명언 격언','$1',NULL);
INSERT INTO "proverbs" VALUES(458,'어려울때 필요한 격언 명언','$1',NULL);
INSERT INTO "proverbs" VALUES(459,'늦게오는 기쁨은 늦게 떠난다. -L.J.베이츠','$1',NULL);
INSERT INTO "proverbs" VALUES(460,'승리를 희망하지 않는 자는 이미 진것이다. -J.J.볼메도','$1',NULL);
INSERT INTO "proverbs" VALUES(461,'후회는 언제 하여도 늦지 않다. -J.레이','$1',NULL);
INSERT INTO "proverbs" VALUES(462,'인생은 어느덧 지나간다.-그러니까 견딜만 하다. -A.체이스','$1',NULL);
INSERT INTO "proverbs" VALUES(463,'인간은 멸망될 수는 있어도 패배당할 수는 없다. -E.헤밍웨이','$1',NULL);
INSERT INTO "proverbs" VALUES(464,'위험은 위험없이는 결코 굴복되지 않는다.','$1',NULL);
INSERT INTO "proverbs" VALUES(465,'부드러운 빗방울은 굵은 대리석을 꿰뚫는다. -J.릴리','$1',NULL);
INSERT INTO "proverbs" VALUES(466,'모든 인간은 자기 운명의 개척자이다. -A.클라우디우스 카에쿠스','$1',NULL);
INSERT INTO "proverbs" VALUES(467,'지금의 나를 과거의 나로 독단하지 마라.','$1',NULL);
INSERT INTO "proverbs" VALUES(468,'폭풍 뒤에는 평온이 온다. -W.대브단트','$1',NULL);
INSERT INTO "proverbs" VALUES(469,'두려움 없는 사람이 가장 빨리 정상에 오른다.','$1',NULL);
INSERT INTO "proverbs" VALUES(470,'모든 사람은 남이 없는 어떤 탁월함이 있다. -푸블릴리우스 시루스','$1',NULL);
INSERT INTO "proverbs" VALUES(471,'인간의 으뜸가는 장점은 자기의 천성의 충동을 억제하는데 있다. -S.존슨','$1',NULL);
INSERT INTO "proverbs" VALUES(472,'승리하는 자는 웃는다. -J.헤이우드','$1',NULL);
INSERT INTO "proverbs" VALUES(473,'일에서 건강이 건강에서 만족이 샘솟는다. 만족은 모든 기쁨의 근원을 열어준다. -J.비티','$1',NULL);
INSERT INTO "proverbs" VALUES(474,'나는 운명을 내 자신에 굴복시키려고 하지내 자신을 운명에 굴복시키 려고 하진 않는다.','$1',NULL);
INSERT INTO "proverbs" VALUES(475,'위험에 대한 공포는 위험 그 자체보다 천배나 무겁다. -P.포우스','$1',NULL);
INSERT INTO "proverbs" VALUES(476,'위험에 도전하는 삶은 위험이 닥치기 전에 제압한다. -푸블리우스 시루스','$1',NULL);
INSERT INTO "proverbs" VALUES(477,'마음속 본심으로서가 아니면 실지로 패배는 없다.-네가 내심에 패배당하지 않는한 너는 틀림없이 이긴다.-H.오스틴','$1',NULL);
INSERT INTO "proverbs" VALUES(478,'희망이 결여되어 있는 자는 살아 있는 가장 가련한 인간이다. -T.풀러','$1',NULL);
INSERT INTO "proverbs" VALUES(479,'당신 스스로가 하지 않으면 아무도 당신의 운명을 개선시켜 주지 않을 것이다. -B.브레히트','$1',NULL);
INSERT INTO "proverbs" VALUES(480,'꿀은 달지만 꿀벌은 쏜다. -G.하버트','$1',NULL);
INSERT INTO "proverbs" VALUES(481,'노고는 인생의 율법이며 인생의 최선의 열매이다. -모리스','$1',NULL);
INSERT INTO "proverbs" VALUES(482,'공부명언 명언 모음 명언모음 명언집 불행할때 명언 사랑명언 성공명언 슬플때 명언 영어명언 우정명언 인생명언 좋은 글귀 좋은명언 지칠때 명언 짧은명언 힘들때 힘들때 명언 힘들때 좋은글 힘들때 좋은글귀 격언 모음 2proo 2proo life story','$1',NULL);
INSERT INTO "proverbs" VALUES(483,'기타 명언들...','$1',NULL);
INSERT INTO "proverbs" VALUES(484,'자기 신뢰가 성공의 제 1의 비결이다. -에머슨','$1',NULL);
INSERT INTO "proverbs" VALUES(485,'미래의 가장 좋은 에언은 과거와 현재이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(486,'오늘의 하나는 내일의 둘의 가치가 있다. -B.프랭크린','$1',NULL);
INSERT INTO "proverbs" VALUES(487,'큰 기쁨은 슬픔처럼 말이 없는 법이다. -S.마이어','$1',NULL);
INSERT INTO "proverbs" VALUES(488,'큰 기쁨은 울고 큰 슬픔은 웃는다. -J.루','$1',NULL);
INSERT INTO "proverbs" VALUES(489,'현명하거든 명랑하라 -마르티알리스','$1',NULL);
INSERT INTO "proverbs" VALUES(490,'천국의 문에는 이렇게 쓰여 있다."운명에 굴복하는 얼빠진 자들에게 슬픔이 있으리." -하피츠에머슨','$1',NULL);
INSERT INTO "proverbs" VALUES(491,'재능은 인간의 능력 속에 있는 것이요 천재는 자신의 능력속에 인간이 있는 것이다. -J.R.로우얼','$1',NULL);
INSERT INTO "proverbs" VALUES(492,'웃어보라세상이 너와 함께 웃을꺼요.울어보라너 혼자 울겠지.','$1',NULL);
INSERT INTO "proverbs" VALUES(493,'서글프고 늙은 이 세상은 환희는 빌려야하고 자신의 고통은 너무 많으니까 말이다.-E.W.윌콕스','$1',NULL);
INSERT INTO "proverbs" VALUES(494,'부끄러움 중에서 가장 나쁜것은 검약과 빈곤을 부끄러워하는 것이다. -리바우스','$1',NULL);
INSERT INTO "proverbs" VALUES(495,'좋은 말이든 나쁜 말이든 세상 사람의 가장 적게 오르는 자가 가장 행복하다. -T. 제어슨','$1',NULL);
INSERT INTO "proverbs" VALUES(496,'사랑에는 눈물이 있고 행운에는 기쁨이 있고 용맹에는 명예가 있으며 야망에는 죽음이 있다.-세익스피어','$1',NULL);
INSERT INTO "proverbs" VALUES(497,'아담도 인간에 지나지 않았다.이 한 마디가 모든 것을 해명한다.','$1',NULL);
INSERT INTO "proverbs" VALUES(498,'그는 사과 그 자체를 위해서 사과를 원한 것이 아니라 그것이 금지된 것이기 때문에 원한 것이다. -마크트웨인','$1',NULL);
INSERT INTO "proverbs" VALUES(499,'자기가 자기를 맏지 않고 타인의 믿음을 바란다는 것은 무리한 일이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(500,'남을 아는 사람은 현명한 사람이다. 자기를 아는 사람은 덕이있는 사람이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(501,'남에게 이기는 사람은 힘이 강한 사람이다. 자기 자신을 이기는 사람은 마음이 굳센 사람이다.','$1',NULL);
INSERT INTO "proverbs" VALUES(502,'성공의 비결은 목적을 향해 시종일관하는 것이다.- 디즈레일리','$1',NULL);
INSERT INTO "proverbs" VALUES(503,'한 가지 일을 경험하지 않으면 한 가지 지혜가 자라지 않는다.- 명심보감','$1',NULL);
INSERT INTO "proverbs" VALUES(504,'가장 높은 곳에 올라가려면','가장 낮은 곳부터 시작하라.- 푸블릴리우스 시루스',NULL);
INSERT INTO "proverbs" VALUES(505,'울지 않는 청년은 야만인이요 웃지 않는 노인은 바보다.- 조지 산타아나','$1',NULL);
INSERT INTO "proverbs" VALUES(506,'은혜를 입은 자는 잊지 말아야 하고 베푼 자는 기억하지 말아야 한다.- 피레 찰론','$1',NULL);
INSERT INTO "proverbs" VALUES(507,'가시에 찔리지 않고서는 장미꽃을 모을 수가 없다.- 필페이','$1',NULL);
INSERT INTO "proverbs" VALUES(508,'한가한 인간은 고여 있는 물이 썩는 것과도 같다.- 프랑스 격언','$1',NULL);
INSERT INTO "proverbs" VALUES(509,'살아 있는 실패작은 죽은 걸작보다 낫다.- 버나드 쇼','$1',NULL);
INSERT INTO "proverbs" VALUES(510,'가장 훌륭한 기술','가장 배우기 어려운 기술은 세상을 살아가는 기술이다.- 메이시',NULL);
INSERT INTO "proverbs" VALUES(511,'여가를 활용하지 못하는 사람은 항상 여가 시간이 없다.- 서양 격언','$1',NULL);
INSERT INTO "proverbs" VALUES(512,'죽음을 두려워하는 나머지 삶을 시작조차 못하는 사람이 많다.- 벤다이크','$1',NULL);
INSERT INTO "proverbs" VALUES(513,'말이 입힌 상처는 칼이 입힌 상처보다 깁다.- 모르코 속담','$1',NULL);
INSERT INTO "proverbs" VALUES(514,'배운 사람은 항상 자기 속에 재산이 있다.- 필래드라스','$1',NULL);
INSERT INTO "proverbs" VALUES(515,'적당주의자가 되지 말라. 그것은 세상에서 가장 위험한 것이다.- 휴그 왈폴','$1',NULL);
INSERT INTO "proverbs" VALUES(516,'편견이란 실효성이 없는 의견이다.- 암브로스 빌','$1',NULL);
INSERT INTO "proverbs" VALUES(517,'기쁨을 주는 사람만이 더 많은 기쁨을 즐길 수 있다.- 알렉산더 듀마','$1',NULL);
INSERT INTO "proverbs" VALUES(518,'당신은 항상 영웅이 될 수 없다. 그러나 항상 사람은 될 수 있다.- 괴테','$1',NULL);
INSERT INTO "proverbs" VALUES(519,'어떤 가치 있는 행동을 하지 아니한 날','그날은 잃은 날이다.- 자콥 보바트',NULL);
INSERT INTO "proverbs" VALUES(520,'좋은 일을 많이 해내려고 기다리는 사람은 하나의 좋은 일도 해낼 수가 없다.- 사무엘 존슨','$1',NULL);
INSERT INTO "proverbs" VALUES(521,'생명이 있는 한','사람은 무엇인가 바랄 수 있다.- 세네카',NULL);
INSERT INTO "proverbs" VALUES(522,'습관은 제2의 천성으로 제1의 천성을 파괴한다.- 파스칼','$1',NULL);
INSERT INTO "proverbs" VALUES(523,'빈부강약을 막론하고 일하지 않는 자를 배척하라.- 루소','$1',NULL);
INSERT INTO "proverbs" VALUES(524,'너 자신을 다스려라. 그러면 당신은 세계를 다스릴 것이다.- 중국 속담','$1',NULL);
INSERT INTO "proverbs" VALUES(525,'작은 구멍 하나가 큰 배를 침몰시키는 것이다.- 에프라임 도마라츠키','$1',NULL);
INSERT INTO "proverbs" VALUES(526,'성실하지 못한 사람은 위대한 것들을 생산할 수가 없다.- 제임스 럿셀 로우웰','$1',NULL);
INSERT INTO "proverbs" VALUES(527,'일을 몰고 가라. 그렇지 않으면 일이 너를 몰고 갈 것이다.- 프랭클린','$1',NULL);
INSERT INTO "proverbs" VALUES(528,'위대한 것 치고 정열이 없이 이루어진 것은 없다.- 에머슨','$1',NULL);
INSERT INTO "proverbs" VALUES(529,'인생을 해롭게 하는 비애를 버리고 명랑한 기질을 간직하라.- 세익스피어','$1',NULL);
INSERT INTO "proverbs" VALUES(530,'우리의 거의 모든 삶이 어리석은 호기심에 낭비되고 있다.- 보들레르','$1',NULL);
INSERT INTO "proverbs" VALUES(531,'조용한 물이 깊이 흐른다.- 릴리','$1',NULL);
INSERT INTO "proverbs" VALUES(532,'다른 사람들을 비난하려고 생각하기 전에 자기 자신을 충분히 살펴보아야 한다.- 몰리에르','$1',NULL);
INSERT INTO "proverbs" VALUES(533,'천재란 인내에 대한 위대한 자질 이외에는 아무 것도 아니다.- 뷰퐁','$1',NULL);
INSERT INTO "proverbs" VALUES(534,'시간을 선택하는 것은 시간을 절약하는 것이다.- 베이컨','$1',NULL);
INSERT INTO "proverbs" VALUES(535,'이해가 부족한 사람이 오해가 많은 사람보다 낫다.- 아나톨 프랑스','$1',NULL);
INSERT INTO "proverbs" VALUES(536,'진정한 위인 치고 자신을 위인으로 생각하는 자는 없다.- 해즐리트','$1',NULL);
INSERT INTO "proverbs" VALUES(537,'폭풍은 참나무가 더욱 뿌리를 깊게 박도록 한다.- 허버트','$1',NULL);
INSERT INTO "proverbs" VALUES(538,'모범은 훈화보다 유효하다.- 영국속담','$1',NULL);
INSERT INTO "proverbs" VALUES(539,'즐거움에 찬 얼굴은 한 접시의 물로도 연회를 만들 수 있다.- 허버트','$1',NULL);
INSERT INTO "proverbs" VALUES(540,'말로 하는 사랑은 쉽게 외면할 수 있으나 행동으로 보여주는 사람은 저항할 수가 없다.- 무니햄','$1',NULL);
INSERT INTO "proverbs" VALUES(541,'성공적인 결혼이란 매일같이 개축해야 하는 건물과 같은 것이다.- 모로아','$1',NULL);
INSERT INTO "proverbs" VALUES(542,'사랑하고 나서 잃는 것은 전혀 사랑하지 않았던 것보다 더 낫다.- 테니슨','$1',NULL);
INSERT INTO "proverbs" VALUES(543,'말하자마자 행동하는 사람','그것이 가치 있는 사람이다.- 엔니우스',NULL);
INSERT INTO "proverbs" VALUES(544,'대화시의 신중은 웅변보다 더 중요하다.- 그라시안','$1',NULL);
INSERT INTO "proverbs" VALUES(545,'양심은 어떠한 과학의 힘보다도 강하고 현명하다.- 라데이러','$1',NULL);
INSERT INTO "proverbs" VALUES(546,'시간을 이용할 줄 아는 사람은 하루를 사흘로 통용한다.- 영국속담','$1',NULL);
INSERT INTO "proverbs" VALUES(547,'충고는 좀처럼 환영받지 못한다.- 체스터필드','$1',NULL);
INSERT INTO "proverbs" VALUES(548,'탐구정신은 우리가 살고 있는 시대의 위대한 특징이다.- 풀','$1',NULL);
INSERT INTO "proverbs" VALUES(549,'지구상에는 인간이외는 위대한 것이 없다. 인간에게는 지성이외엔 훌륭한 것이 없다.- 헤밀턴','$1',NULL);
INSERT INTO "proverbs" VALUES(550,'험한 언덕을 오르려면 처음에는 서서히 걸어야 한다.- 세익스피어','$1',NULL);
INSERT INTO "proverbs" VALUES(551,'정직한 노동은 사랑스런 얼굴을 낳는다.- 대커','$1',NULL);
INSERT INTO "proverbs" VALUES(552,'인간은 이성적 동물이다.- 세네카','$1',NULL);
INSERT INTO "proverbs" VALUES(553,'모범은 모든 사람이 읽을 수 있는 교훈이다.- 웨스트','$1',NULL);
INSERT INTO "proverbs" VALUES(554,'일은 시작할 때가 언제나 가장 좋다.- 파스칼','$1',NULL);
INSERT INTO "proverbs" VALUES(555,'두 사람의 머리는 한 사람의 머리보다 낫다.- 헤이우드','$1',NULL);
INSERT INTO "proverbs" VALUES(556,'탐구하여 찾아질 수 없을 정도로 어려운 문제는 존재하지 않는다.- 티랜티우스','$1',NULL);
INSERT INTO "proverbs" VALUES(557,'아이들에게는 비평보다도 귀감이 필요하다.- 쥬벨','$1',NULL);
INSERT INTO "proverbs" VALUES(558,'큰 나무는 바람을 많이 받는다.- 카네기','$1',NULL);
INSERT INTO "proverbs" VALUES(559,'한 시대의 철학은 다음 시대에서는 평범한 상식에 불과하다.- 헨리 W. 비치','$1',NULL);
INSERT INTO "proverbs" VALUES(560,'나는 나 자신을 빼 놓고는 모두 안다.- 비용','$1',NULL);
INSERT INTO "proverbs" VALUES(561,'강한 사람이란 가장 훌륭하게 고독을 견디어 낸 사람이다.- 쉴러','$1',NULL);
INSERT INTO "proverbs" VALUES(562,'만약 급히 서두르려면 돌아가는 길로 가라.- 영국속담','$1',NULL);
INSERT INTO "proverbs" VALUES(563,'안심하면서 먹는 한 조각 빵이 근심하면서 먹는 잔치보다 낫다.- 이솝','$1',NULL);
INSERT INTO "proverbs" VALUES(564,'미지를 향해 출발하는 사람은 누구나 외로운 모험에 만족해야 한다.- 지드','$1',NULL);
INSERT INTO "proverbs" VALUES(565,'기와 한 장 아껴서 대들보 썩는다.- 한국속담','$1',NULL);
INSERT INTO "proverbs" VALUES(566,'핑계를 잘 대는 사람은 거의 좋은 일을 하나도 해내지 못한다.- 벤자민 프랭클린','$1',NULL);
INSERT INTO "proverbs" VALUES(567,'겸손이 없다면 당신은 인생의 가장 기본적인 교훈도 배울 수가 없다.- 존 톰슨','$1',NULL);
INSERT INTO "proverbs" VALUES(568,'작은 성공을 만족스럽게 생각하는 사람은 큰 성공을 얻지 못한다.- 제세 메서 게만','$1',NULL);
INSERT INTO "proverbs" VALUES(569,'존재하는 것을 변화시키는 것은 성숙하게 만드는 것이다.- 헨리 버그슨','$1',NULL);
INSERT INTO "proverbs" VALUES(570,'인격은 당신의 아이들에게 남겨줄 수 있는 최대의 유산이다.- 아놀드 그라소우','$1',NULL);
INSERT INTO "proverbs" VALUES(571,'인내하라. 경험하라. 조심하라. 그리고 희망을 가져라.- 조셉 에디슨','$1',NULL);
INSERT INTO "proverbs" VALUES(572,'위대한 사람은 절대로 기회가 부족하다고 불평하지 않는다.- 에머슨','$1',NULL);
INSERT INTO "proverbs" VALUES(573,'잔잔한 바다에서는 좋은 뱃사공이 만들어지지 않는다.- 영국속담','$1',NULL);
INSERT INTO "proverbs" VALUES(574,'확실한 벗은 불확실한 처지에 있을 때 알려진다.- 시세로','$1',NULL);
INSERT INTO "proverbs" VALUES(575,'사랑하고 사랑 받는 것은 태양을 양쪽에서 쪼이는 것과 같다.- 비스코트','$1',NULL);
INSERT INTO "proverbs" VALUES(576,'지성이란 그것을 갖고 있지 않는 사람에게는 보이지 않는다.- 쇼펜하우어','$1',NULL);
INSERT INTO "proverbs" VALUES(577,'분노는 바보들의 가슴속에서만 살아간다.- 아인슈타인','$1',NULL);
CREATE TABLE TABLE_NAME(
  content VARCHAR(100),
  author VARCHAR(100),
  COLUMN3 VARCHAR(100),
  COLUMN4 VARCHAR(100),
  COLUMN5 VARCHAR(100)
);
CREATE TABLE images ( id integer PRIMARY KEY AUTOINCREMENT
, image_name varchar(255)

, extension default '.jpg');
INSERT INTO "images" VALUES(18,'sdlkfsldkf.jpg','.jpg');
INSERT INTO "images" VALUES(19,'20170613000101_0.jpg','jpg');
INSERT INTO "images" VALUES(20,'3966_8164_4723.jpg','jpg');
INSERT INTO "images" VALUES(21,'a0001620_5812066d73468.jpg','jpg');
INSERT INTO "images" VALUES(22,'averie-woodard-111832.jpg','jpg');
INSERT INTO "images" VALUES(23,'a0001620_5812066d73468.png','png');
CREATE TABLE receipe(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  title  varchar(255),
  material varchar(255),
  image varchar(100),
  url varchar(255),
  create_dt varchar(100)

);
INSERT INTO "receipe" VALUES(1,'육해공 연볶이','떢복기,햄, 김밥,라면','Screenshot_2016-02-02-09-34-55.png','https://m.blog.naver.com/bird_6969/220615980613','2017-09-28');
INSERT INTO "receipe" VALUES(6,'옥수스웨그 팬케이크','옥수수, 밀가루,시럽','fan_cake.png','https://m.blog.naver.com/bird_6969/220621924069','2017-09-28');
INSERT INTO "receipe" VALUES(22,'동그랑떙','동그랑떙','1.JPG','http://blog.naver.com/yoonjs3/221107649142','2017-09-29');
INSERT INTO "receipe" VALUES(23,'집밥백선생 탄탄면','재료: 물, 라면, 땅콩버터, 고춧가루, 대파','tantan-myun.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=6964749','2017-09-29');
INSERT INTO "receipe" VALUES(24,'집밥백선생 컵빵 만들기','재료: 버터, 마요네즈, 설탕, 달걀, 소금, 통조림옥수수, 양파, 빵, 모차렐라치즈','cup_bread.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=9792614&memberNo=19357942','2017-09-29');
INSERT INTO "receipe" VALUES(25,'집밥백선생 스테이크 굽기','[재료: 스테이크용 소고기, 맛소금, 굵은 후춧가루, 올리브유]','stake.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=8485211&memberNo=19357942','2017-09-29');
INSERT INTO "receipe" VALUES(26,'집밥백선생 액젓불고기','[재료: 불고기용 소고기, 양파, 대파, 당근, 새송이버섯, 설탕, 피쉬소스, 간 마늘, 참기름]','액젖불고기.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=8596232&memberNo=19357942','2017-09-29');
INSERT INTO "receipe" VALUES(27,'집밥백선생 깐풍새우 만들기','[재료: 새우, 감자전분가루, 물, 양파, 당근, 고추, 대파, 사천고추, 식용유, 진간장, 설탕, 식초, 굴소스]','kkang_ppung_seu.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=8596283&memberNo=19357942','2017-09-29');
INSERT INTO "receipe" VALUES(28,'집밥백선생 모둠전 만들기.','[재료: 간 소고기, 양파, 당근, 고추, 대파, 설탕, 액젓, 간 마늘, 굴소스, 참기름, 달걀, 부침가루, 깻잎, 두부, 고추, 호박, 불고기용 소고기, 식용유]','doeum_jeon.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=8596370&memberNo=19357942','2017-09-29');
INSERT INTO "receipe" VALUES(29,'집밥백선생 라면전 만들기.','[재료: 라면, 물, 대파, 식용유, 꿀, 모차렐라 치즈]','ramen_jeon1.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=6964700&memberNo=19357942','2017-09-29');
INSERT INTO "receipe" VALUES(30,'집밥백선생 불맛짬뽕라면 만들기.','재료: 물, 양배추, 양파, 대파, 식용유, 대패삼겹살, 라면, 고춧가루, 진간장','bul-jjang-bong.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=6964791&memberNo=19357942','2017-09-29');
INSERT INTO "receipe" VALUES(31,'집밥백선생 두부스크램블(+두부스크램블 샌드위치) 만들기.','재료 : 베이컨, 달걀, 대파, 두부, 식용유, 버터, 소금, 체더 슬라이스 치즈, 후춧가루, 식빵, 케첩]','dooboo_scream.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=7043570&memberNo=19357942','2017-09-29');
INSERT INTO "receipe" VALUES(32,'김풍''s 토달토달 ','토마토 큰거 2개 / 방울은 20~25개 정도 적당,  식빵 2장, 계란 1개, 마늘 4~5쪽, 사골라면스프 1, 진간장 1/2, 맛술1(소주나 미림 등으로 대체가능), 식초 1/2, 참기름 1, 후추, 전분가루 1 옵션 :: 레몬즙 1, 고춧가루 취향껏, 소금 조금    [ 1 = 1큰술 = 15ml / 밥수저계량 동일 ]','todal_todal.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=2096095&memberNo=7089880&clipNo=6&searchKeyword=%EB%83%89%EC%9E%A5%EA%B3%A0%EB%A5%BC%EB%B6%80%ED%83%81%ED%95%B4%EB%A0%88%EC%8B%9C%ED%94%BC&searchRank=2','2017-09-29');
INSERT INTO "receipe" VALUES(33,'감자요리, 아코디언감자 만들기','감자, 양념','accordion_potato.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=9410767&memberNo=7089880','2017-09-29');
INSERT INTO "receipe" VALUES(34,'소갈비찜 황금레시피 ','소갈비, 표고버섯 , 밤, 대추 ,당근, 배 , 양파 ,홍코추, 참기름..','DSC04383.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=9408281&memberNo=7089880','2017-09-29');
INSERT INTO "receipe" VALUES(35,'표고버섯요리','버섯','phogo.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=9408119&memberNo=7089880','2017-09-29');
INSERT INTO "receipe" VALUES(36,'꼬마김밥만들기','재 료 준 비    밥 3공기정도 → 밑간 :: 식초1T, 설탕1t, 소금 1/3t   당근, 소고기, 단무지, 오이(옵션)  간장, 올리고당, 다진마늘, 고추가루, 식초, 설탕, 후추, 김.밥.용.김 자세한 비율은 아래에♩   [1T = 1큰술, 1t = 1작은술 의미]','ggoma_gim.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=1092105&memberNo=7089880&clipNo=6','2017-09-29');
INSERT INTO "receipe" VALUES(37,'오뎅볶음 황금레시피, 매운 양념으로','납작한 어묵 8장 정도, 양파 1/2개, 땡초나 꽈리고추 한줌 (옵션/없으면 PASS),  ﻿진간장 3, 다진마늘 1/2, 고춧가루 1, 소주나 맛술 1, 설탕 2/3, 올리고당 1, 물 5~6, 생강가루, 후추(선택사항), 통깨 조금  ﻿[ 1 = 1큰술 = 15ml / 밥수저계량 ]','odeng.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=2418273&memberNo=7089880&clipNo=29','2017-09-29');
INSERT INTO "receipe" VALUES(38,'피클만드는법 세상에서 젤 쉬워','백다다기오이 3개 정도, 무 1/3개, 당근 1개, 기호에 따라 양배추나 양파도 OK 피클링스파이스 1, 물 600ml, 설탕 300ml, 식초 280ml(물 : 설탕 : 식초 = 2 : 1 : 1보다 조금 적게), 소금 1.5, 유리병  옵션 ::레몬슬라이스이나 즙   [ 1 = 1큰술 = 15ml / 밥수저 계량 ]','pikel.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=2434798&memberNo=7089880&clipNo=7','2017-09-29');
INSERT INTO "receipe" VALUES(39,'Good Change!! 진라면 맛있게 끓이는법','진라면, 계란, 파채, 홍고추,버섯,마늘','ramen_jeon2.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=9717465&memberNo=7089880','2017-09-29');
INSERT INTO "receipe" VALUES(40,'오세득 돼새찌개','','pig_jjige.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=3793156&memberNo=571&searchKeyword=%EB%83%89%EC%9E%A5%EA%B3%A0%EB%A5%BC%EB%B6%80%ED%83%81%ED%95%B4%EB%A0%88%EC%8B%9C%ED%94%BC&searchRank=4','2017-09-29');
INSERT INTO "receipe" VALUES(41,'참치샌드위치 ','','tuna_sandwitch.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=8108685&memberNo=571','2017-09-29');
INSERT INTO "receipe" VALUES(42,'떡갈비 피자','떡갈비피자 재료 소개  또르티아 2장, 남은 떡갈비 산적 2개, 파프리카, 양파, 피망 모두 1/4개 모짜렐라치즈 1/2컵, 돈가스소스 2큰술, 올리브, 파슬리 약간','galbi_duk.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=9843034&memberNo=571&navigationType=push','2017-09-30');
INSERT INTO "receipe" VALUES(43,'집밥백선생 깐풍새우 만들기.','[재료: 새우, 감자전분가루, 물, 양파, 당근, 고추, 대파, 사천고추, 식용유, 진간장, 설탕, 식초, 굴소스]','mug_obj_149978129403317167.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=8596283&memberNo=19357942','2017-09-30');
INSERT INTO "receipe" VALUES(44,'고추장제육볶음 : 저렴하게 앞다리살로!','','jeeyuk.jpg','http://m.post.naver.com/viewer/postView.nhn?volumeNo=1889781&memberNo=1267558&vType=VERTICAL','2017-10-02');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('proverbs',577);
INSERT INTO "sqlite_sequence" VALUES('images',23);
INSERT INTO "sqlite_sequence" VALUES('receipe',44);
COMMIT;
