---



grails:


    controllers:
        upload:
            maxFileSize: 26214400
            maxRequestSize: 26214400
    profile: web
    codegen:
        defaultPackage: grails001
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    jpa:
      database-platform:

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true
server:
  port: 8000




---
grails:
    cors:
        enabled: true
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    format_sql: true
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

datasource:
 properties :
      maxActive : 50
      maxIdle : 25
      minIdle : 1
      initialSize : 1
      numTestsPerEvictionRun : 3
      maxWait : 10000
      testOnBorrow : true
      testWhileIdle : true
      testOnReturn : true
      validationQuery : "select now()"
      minEvictableIdleTimeMillis : 1000 * 60 * 5
      timeBetweenEvictionRunsMillis : 1000 * 60 * 5


##################
#mysql source
##################
environments:
    development:
        uploadFolder : "d:/upload/"
        dataSource:
            #dbCreate: create-drop
            dbCreate: update
            driverClassName : com.mysql.jdbc.Driver
            username: root
            password: 1114
            logSql: true
            url: jdbc:mysql://104.199.239.95:3306/grails001?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
            #url: jdbc:mysql://localhost:3306/grails001
    test:
        uploadFolder : "d:/upload/"
        dataSource:
            dbCreate: update
            logSql: true
            driverClassName : com.mysql.jdbc.Driver
            username: root
            password: 1114
            url: jdbc:mysql://104.199.239.95:3306/grails001?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    production:
        uploadFolder : "/home/springboot12345/upload/"
        dataSource:
            dbCreate: update
            logSql: true
            driverClassName : com.mysql.jdbc.Driver
            username: root
            password: 1114
            url: jdbc:mysql://104.199.239.95:3306/grails001?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&useSSL=false


